title = "Test Config"

# gl.type determines how to pass the uniforms
# ui.type determines what component to use

[[uniforms]]
name = "A Float Uniform"
[uniforms.gl]
type = "float"
name = "iFloat"
[uniforms.ui]
type = "slider"
value = 0.6
min = 0
max = 1
step = 0.1

[[uniforms]]
name = "A Bool Uniform"
[uniforms.gl]
type = "bool"
name = "iBool"
[uniforms.ui]
type = "checkbox"
value = true

[[uniforms]]
name = "A Color Uniform"
[uniforms.gl]
type = "color4"
name = "iColor"
[uniforms.ui]
type = "color"
value = "#3498db"
