title = "Test Config"

[[uniforms]]
name = "Outer"
[uniforms.ui]
type = "folder"
value = true # folded or not

[[uniforms.children]]
name = "Outer Shape"
[uniforms.children.gl]
type = "int"
name = "iShape"
[uniforms.children.ui]
type = "dropdown"
value = 0
options = ["Square", "Circle", "Diamond"]

[[uniforms.children]]
name = "Background Color"
[uniforms.children.gl]
type = "color4"
name = "iBackgroundColor"
[uniforms.children.ui]
type = "color"
value = "ffffff"

[[uniforms.children]]
name = "Outline Color"
[uniforms.children.gl]
type = "color4"
name = "iOutlineColor"
[uniforms.children.ui]
type = "color"
value = "000000"

[[uniforms.children]]
name = "Outline Thickness"
[uniforms.children.gl]
type = "float"
name = "iOutlineThickness"
[uniforms.children.ui]
type = "slider"
value = 0.1
min = 0
max = 0.2
step = 0.001



[[uniforms]]
name = "Checker"
[uniforms.ui]
type = "folder"
value = true # folded or not

[[uniforms.children]]
name = "Number of Checkers"
[uniforms.children.gl]
type = "int"
name = "iNumCheckers"
[uniforms.children.ui]
type = "slider"
value = 5
min = 0
max = 20
step = 1

[[uniforms.children]]
name = "Checker Color 1"
[uniforms.children.gl]
type = "color3"
name = "iColor1"
[uniforms.children.ui]
type = "color"
value = "#ffffff"

[[uniforms.children]]
name = "Checker Color 2"
[uniforms.children.gl]
type = "color3"
name = "iColor2"
[uniforms.children.ui]
type = "color"
value = "#000000"



[[uniforms]]
name = "Stripe"
[uniforms.ui]
type = "folder"
value = true # folded or not

[[uniforms.children]]
name = "Number of Stripes"
[uniforms.children.gl]
type = "int"
name = "iNumStripes"
[uniforms.children.ui]
type = "slider"
value = 5
min = 0
max = 20
step = 1

[[uniforms.children]]
name = "Stripe Color 1"
[uniforms.children.gl]
type = "color3"
name = "iStripeColor1"
[uniforms.children.ui]
type = "color"
value = "#ffffff"

[[uniforms.children]]
name = "Stripe Color 2"
[uniforms.children.gl]
type = "color3"
name = "iStripeColor2"
[uniforms.children.ui]
type = "color"
value = "#000000"