title = "Test Config"

[[uniforms]]
name = "Number of Checkers"
[uniforms.gl]
type = "int"
name = "iNumCheckers"
[uniforms.ui]
type = "slider"
value = 5
min = 0
max = 20
step = 1

[[uniforms]]
name = "Checker Color 1"
[uniforms.gl]
type = "color3"
name = "iColor1"
[uniforms.ui]
type = "color"
value = "#ffffff"

[[uniforms]]
name = "Checker Color 2"
[uniforms.gl]
type = "color3"
name = "iColor2"
[uniforms.ui]
type = "color"
value = "#000000"